language: scala
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: (branch = master) AND (type = push)

jobs:
  include:
    # default stage is test
    - env: TEST="scalafmt"
      script: ./bin/scalafmt --test
    - env: TEST="2.11"
      script:
        - sbt ++2.11.12 lsp4s/test
        - sbt ++2.11.12 jsonrpc/test
    - env: TEST="sbt test"
      script:
        - sbt startServer metalsSetup test scalafixTest
    - env: TEST="sbt-metals"
      script:
        - sbt ^sbt-metals/compile
    - stage: release
      script: ./bin/release.sh

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
