version: '{build}'
os: Windows Server 2012
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
build_script:
  - sbt version # dummy step, a build_script step is required by appveyor.
test_script:
  - sbt unit/test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier
  - C:\Users\appveyor\.cache
  - C:\Users\appveyor\.sbt
