version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: sbt version & exit 0
  - cmd: sbt version & exit 0
environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"
  JAVA_OPTS: -Djna.nosys=true
build_script:
  - sbt publishLocal
test_script:
  - sbt test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.coursier
  - C:\Users\appveyor\.cache
  - C:\Users\appveyor\.sbt
