name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: windows-latest
            java: 8
          - os: macOS-latest
            java: 8
        include:
          - os: ubuntu-latest
            CACHE_PATH: ~/.cache/coursier/v1
          - os: macOS-latest
            CACHE_PATH: ~/Library/Caches/Coursier/v1
          - os: windows-latest
            CACHE_PATH: ~\AppData\Local\Coursier\Cache\v1
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: actions/cache@v1
        with:
          path: $CACHE_PATH
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run unit tests
        run: |
          bin/test.sh unit/test
        shell: bash
  sbt:
    name: Sbt integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run Sbt tests
        run: bin/test.sh 'slow/testOnly -- tests.sbt'
  maven:
    name: Maven integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run Maven tests
        run: bin/test.sh 'slow/testOnly -- tests.maven'
  gradle:
    name: Gradle integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run Gradle tests
        run: bin/test.sh 'slow/testOnly -- tests.gradle'
  mill:
    name: Mill integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run Mill tests
        run: bin/test.sh 'slow/testOnly -- tests.mill'
  pants:
    name: Pants integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run Pants tests
        run: bin/test.sh 'slow/testOnly -- tests.pants'
  feature:
    name: LSP integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run LSP tests
        run: bin/test.sh 'slow/testOnly -- tests.feature'
  cross:
    name: Scala cross tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - name: Run cross tests
        run: sbt +cross/test
  checks:
    name: Scalafmt/Scalafix/Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/setup-node@v1
      - run: git fetch --depth=10000
      - run: git fetch --tags
      - name: Scalafmt & Scalafix & Docusaurus
        run: |
          ./bin/scalafmt --test
          sbt scalafixCheck docs/docusaurusCreateSite
