name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: windows-latest
            java: 8
          - os: macOS-latest
            java: 8
        include:
          - os: ubuntu-latest
            CACHE_PATH: ~/.cache/coursier/v1
          - os: macOS-latest
            CACHE_PATH: ~/Library/Caches/Coursier/v1
          - os: windows-latest
            CACHE_PATH: ~\AppData\Local\Coursier\Cache\v1
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: actions/cache@v1
        with:
          path: $CACHE_PATH
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run unit tests
        run: |
          bin/test.sh unit/test
        shell: bash
  integration:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          [sbt, maven, gradle, pants, mill, feature, cross, scalafmt, scalafix]
        include:
          - type: sbt
            command: bin/test.sh 'slow/testOnly -- tests.sbt'
            name: Sbt integration
          - type: maven
            command: bin/test.sh 'slow/testOnly -- tests.maven'
            name: Maven integration
          - type: gradle
            command: bin/test.sh 'slow/testOnly -- tests.gradle'
            name: Gradle integration
          - type: pants
            command: bin/test.sh 'slow/testOnly -- tests.pants'
            name: Pants integration
          - type: mill
            command: bin/test.sh 'slow/testOnly -- tests.mill'
            name: Mill integration
          - type: feature
            command: bin/test.sh 'slow/testOnly -- tests.feature'
            name: LSP integration tests
          - type: cross
            command: sbt +cross/test
            name: Scala cross tests
          - type: scalafix
            command: sbt scalafixCheck docs/docusaurusCreateSite
            name: Scalafix and docs
          - type: scalafmt
            command: ./bin/scalafmt --test
            name: Formatting
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.11"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: ${{ matrix.command }}
        run: ${{ matrix.command }}
